plugins {
	id 'fabric-loom' version '1.18.2'
}

version = project.mod_version
group = project.maven_group
def expandedModVersion = version.toString()

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
}

processResources {
	inputs.property 'version', expandedModVersion
	filesMatching('fabric.mod.json') {
		expand 'version': expandedModVersion
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}
